### ISSUE TITLE
postgresql-index-tipleri-ve-index-secimi

### ISSUE THREAD

**Issue by G-khan** [G-khan/g-khan.github.io#3]

**Comment by G-khan** [comment]
test

**Comment by G-khan** [comment]
**First** indexing comment.

**Comment by murataydinw** [comment]
Merhaba,

Bir soru sorabilir miyim?
30m rows'luk bir tablom var diyelim en cok ziyaret edilen 20 rowsu almam gerekiyor where limit 20 order by visitor desc yaparak aliyorum fakat tahmin edersiniz biraz yavas(3-4sec).bunu indexlemek icin ne onerirsiniz order by kullanamiyorum sanirim partial indexlerde

**Comment by G-khan** [comment]
> Merhaba,
> 
> Bir soru sorabilir miyim? 30m rows'luk bir tablom var diyelim en cok ziyaret edilen 20 rowsu almam gerekiyor where limit 20 order by visitor desc yaparak aliyorum fakat tahmin edersiniz biraz yavas(3-4sec).bunu indexlemek icin ne onerirsiniz order by kullanamiyorum sanirim partial indexlerde

Selamlar Murat,
https://gokhana.dev/postgresql-index-tipleri-ve-index-secimi/ burada comment sistemini değiştirdim ve sayfada cevap verdim. çok teşekkürler değerli yorumun için.
